In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# Loading the dataset
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/MultilingualFakeNews/data/english_clean.csv"
)

print(df.shape)
df.head()

(588, 2)

                                                text  target
0   Roger Federer beats Frances Tiafoe on return ...       0
1  'It was a long time coming': Heidi Klum ends s...       1
2  Liam Payne Just Dissed Harry Styles' Solo Musi...       1
3  We all know why the right is angry at Tomi Lah...       0
4  Inside Beyoncé's baby shower Don't act like yo...       0

In [4]:
# Inspecting text lengths
df["length"] = df["text"].apply(len)

df["length"].describe()

count     588.000000
mean      486.998299
std       335.866062
min        56.000000
25%       231.000000
50%       373.000000
75%       674.750000
max      1993.000000
Name: length, dtype: float64

In [5]:
import re

# Basic Text Cleaner
def clean_text(text):

    text = str(text)

    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"\s+", " ", text)

    return text.strip()

In [6]:
df["text"] = df["text"].apply(clean_text)

In [7]:
# Save the clean dataset
df.to_csv(
    "/content/drive/MyDrive/MultilingualFakeNews/data/english_clean_v2.csv",
    index=False
)

In [8]:
df["length"].describe()

count     588.000000
mean      486.998299
std       335.866062
min        56.000000
25%       231.000000
50%       373.000000
75%       674.750000
max      1993.000000
Name: length, dtype: float64